### ISSUE TITLE
Support for Angular 1.5.x

### ISSUE THREAD

**Issue by MaxXxiMast** [Jimdo/angular-fontselect#60]
I am working on a project using angular 1.6.4 and on using the this directive it throws an error stating 
TypeError: self.$http(...).success is not a function
    at FontsService._initGoogleFonts (angular-fontselect.js:2917)
    at new controller (angular-fontselect.js:1955)
    at Object.invoke (angular.js:5003)
    at S.instance (angular.js:10866)
    at n (angular.js:9746)
    at angular.js:10154
    at angular.js:16832
    at m.$digest (angular.js:17971)
    at m.$apply (angular.js:18269)
    at l (angular.js:12387)

Beyond angular 1.5+ the $http service no longer supports the .success()
